SciPy: Linear algebra functions using Numpy and Scipy.

Simultaneous Equations

In [1]:
import sys
!{sys.executable} -m pip install scipy

In [2]:
!/usr/bin/python3 -m pip install scipy

Defaulting to user installation because normal site-packages is not writeable


In [3]:
#import scipy and numpy
from scipy import linalg
import numpy as np

In [4]:
import numpy
numpy.version.version

'1.22.0'

2w + x + 4y + 3z = 5
w - 2x + 3z = 3
3w + 2x - y + z = -1
4x - 5z = -3

In [5]:
A = [[2,1,4,3],[1,-2,0,3],[3,2,-1,1],[0,4,0,5]]
Y = [5,3,-1,3]

result = linalg.solve(A,Y)
print(result)

[-0.15384615 -0.30769231  0.76923077  0.84615385]


Finding a Determinant

In [6]:
b = np.array([[1,5],[2,3]])
x = linalg.det(b)


In [7]:
x

-7.0

Eigen Values and Eigen Vectors

In [8]:
l,v = linalg.eig(b)

In [9]:
#eigen Values
l

array([-1.31662479+0.j,  5.31662479+0.j])

In [10]:
#eigen Vectors
v

array([[-0.90734164, -0.7569396 ],
       [ 0.42039403, -0.65348485]])

In [11]:
from scipy.constants import pi

In [12]:
print("%.5f"%pi)

3.14159
