In [1]:
#importing 
import numpy as np
from numpy import *

In [2]:
ar1 = np.array([1,2,3,4,5])
ar1

array([1, 2, 3, 4, 5])

In [3]:
type(ar1)

numpy.ndarray

In [4]:
a = linspace(10,7,5)
a

array([10.  ,  9.25,  8.5 ,  7.75,  7.  ])

In [5]:
b = logspace(1,4,5)
b

array([   10.        ,    56.23413252,   316.22776602,  1778.27941004,
       10000.        ])

In [6]:
c= arange(3,7,0.5)
c

array([3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5])

In [7]:
zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
ones(6)

array([1., 1., 1., 1., 1., 1.])

In [9]:
np.sin([0,1])

array([0.        , 0.84147098])

In [10]:
np.log10(100)

2.0

In [11]:
np.sort([4,7,3,2])

array([2, 3, 4, 7])